# Generated by Django 5.1.1 on 2024-09-14 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('permite_recorrencia', models.BooleanField()),
                ('quantidade_recorrencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('intervalo_recorrencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status_recorrencia', models.CharField(max_length=50)),
                ('agencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('conta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_pagamento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
